# Truth & Dare prompt pools for an online college group.
# All entries are doable purely over chat — screenshots, texts, calls, group actions.
# No physical/in-person dares. Add your own group-specific ones freely.

TRUTHS = [
    "What's the most embarrassing thing that's happened to you on campus?",
    "Have you ever lied to get out of an assignment? What was it?",
    "Who's your secret campus crush, past or present?",
    "What's a rumor about yourself you wish was true?",
    "What's the worst grade you've ever gotten and how did you react?",
    "Have you ever cheated in an exam? Tell the truth.",
    "What's the most awkward thing you've done in front of a professor?",
    "Who in this group would you trust with a secret, and why?",
    "What's a lie you've told your parents about college?",
    "What's the weirdest thing you've searched online this month?",
    "What's the last lie you told in this group?",
    "Who's the last person you stalked on social media?",
    "What's a nickname you've been called that you hate?",
    "What's the most childish thing you still do?",
    "Have you ever pretended to be sick to skip class? How many times?",
    "What's a subject you're pretending to understand right now?",
    "What's the longest you've gone without replying to someone on purpose?",
    "Who do you complain about most in your DMs?",
    "What app do you spend the most time on that you're slightly ashamed of?",
    "Have you ever screenshotted someone's chat to show a friend? Who?",
    "What's your most used emoji and why?",
    "What's a secret talent nobody in this group knows about?",
    "Have you ever had a crush on someone in this group?",
    "What's the pettiest reason you've ever unfollowed someone?",
    "What's a class you've never actually attended but passed?",
    "What's the most embarrassing thing in your search history?",
    "Have you ever faked being busy to avoid someone in this group?",
    "What's a group project you contributed nothing to?",
    "Who's the last person you cried in front of, or wanted to?",
    "What's your honest opinion of the person above you in the turn order?",
    "What's the last thing you Googled about yourself?",
    "Have you ever read someone's chat over their shoulder on purpose?",
    "What's a habit of yours that annoys your roommate/family?",
    "What's the most dramatic thing you've done over a small issue?",
    "Have you ever ghosted someone in this group chat?",
    "What's a compliment you fish for but never say out loud?",
    "What's the weirdest thing you've bought online at 2 AM?",
    "Who do you think is the funniest person in this group, honestly?",
    "What's a fear you've never told anyone?",
    "Have you ever pretended to like a gift you hated?",
    "What's the last thing you lied about to look cooler?",
    "What's a song you're embarrassed to admit you love?",
    "Have you ever stalked an ex's (or crush's) new partner online?",
    "What's the most awkward voice note you've ever sent?",
    "What's something you do when no one's watching that you'd never admit?",
    "Who's the last person you vented about someone else to?",
    "What's the biggest exaggeration on your resume/LinkedIn?",
    "What's a group chat you've muted forever but never left?",
    "What's the most embarrassing autocorrect fail you've sent?",
    "Have you ever texted the wrong person something private? What happened?",
    "What's a class topic you still don't understand at all?",
    "What's the last thing you regret posting online?",
    "Who's someone in this group you'd want to switch places with for a day?",
    "What's your most irrational fear?",
    "Have you ever taken credit for someone else's work?",
    "What's the most trouble you've been in with your parents?",
    "What's a text you typed but never sent?",
    "What's the last white lie you told a teacher/professor?",
    "Who's the most overrated person you know personally?",
    "What's something about yourself you'd change if you could?",
    "Have you ever pretended to have read something you never opened?",
    "What's the last thing that made you ugly-cry laughing?",
    "What's a purchase you regret the most?",
    "Have you ever eavesdropped on a conversation that wasn't meant for you?",
    "What's the most embarrassing thing your parents have seen on your phone?",
    "What's a lie you tell yourself often?",
    "Who's the last person you blocked and why?",
    "What's your biggest insecurity that you rarely talk about?",
    "Have you ever taken a screenshot of a chat just to show it to someone else as gossip?",
    "What's the weirdest dream you've had about someone in this group?",
    "What's a topic you always argue about, even when you're wrong?",
    "What's the last excuse you gave for being late?",
    "Have you ever liked an old photo by accident while stalking someone?",
    "What's something you pretend to hate but secretly enjoy?",
    "Who do you think has a crush on someone in this group?",
    "What's your most toxic trait, honestly?",
    "What's a rule in this group you've broken silently?",
    "Have you ever faked a laugh to fit in?",
    "What's the last thing you Googled that you'd never say out loud?",
    "What's a message you've drafted but deleted before sending?",
    "Who's the last person you were jealous of and why?",
    "What's the most useless thing you've learned in college?",
    "Have you ever pretended not to see someone's message on purpose?",
    "What's your go-to lie when you don't want to attend an event?",
    "What's a moment you wish you could redo?",
    "Have you ever snooped through someone's phone when they left it unlocked?",
    "What's the most dramatic text you've ever sent?",
    "What's something you're proud of that you never talk about?",
    "Who do you think talks the most in this group but says the least?",
    "What's the last thing you complained about that wasn't really a big deal?",
    "What's a childhood memory that still embarrasses you?",
    "Have you ever pretended to be someone else online?",
    "What's the most impulsive thing you've bought this year?",
    "What's a secret nickname you have for someone in this group?",
    "Have you ever cried during an online class and muted your mic?",
    "What's the last thing you lied about to avoid an argument?",
    "What's a class you took just because your crush was in it?",
    "Who's the last person you screenshotted a story of, just to laugh at it privately?",
    "What's something you've never admitted to your best friend?",
    "What's the last thing you screenshotted 'just in case' you needed proof later?",
]

DARES = [
    "Send a voice note singing the first line of any Bollywood song, right now.",
    "Text your crush (or a random contact) 'I have something to tell you' and screenshot the reply.",
    "Do your best impression of a professor from this college, as a voice note.",
    "Change your display name to something silly for the next 10 minutes.",
    "Send the 5th photo in your gallery, no matter what it is.",
    "Type your next 3 messages using only emojis.",
    "Send your current battery percentage and screen time as your reply.",
    "Let the group pick your profile picture for the next hour.",
    "Send a screenshot of your most recent search history (blur anything too personal).",
    "Send the last text you sent to your mom/dad, screenshotted.",
    "Post the last meme you saved in your gallery.",
    "Send a screenshot of your Spotify/YouTube 'recently played'.",
    "Do a 15-second impression of someone in this group and send it as a voice note.",
    "Send a screenshot of your phone's home screen right now.",
    "Text 'I miss you' to the 3rd contact in your recent chats and screenshot their reply.",
    "Post your camera roll's most recent screenshot, unedited.",
    "Send a voice note reciting the alphabet backwards as fast as you can.",
    "Reply to the next 3 messages using only voice notes, no text.",
    "Send a screenshot of your last Google search.",
    "Change your profile picture to a random emoji for the next 30 minutes.",
    "Send the group your most-used sticker or GIF right now.",
    "Post a screenshot of the last argument/debate you had in any chat (names blurred).",
    "Record yourself talking in an accent for 10 seconds and send it.",
    "Send a voice note pretending to be a news anchor reporting on this group.",
    "Send your most recent voice note to anyone, exactly as it is, to this group.",
    "Type your next message in all caps, no matter what it is.",
    "Send a screenshot showing how many unread chats you currently have.",
    "Reply to every message for the next 5 minutes using only 'yes' or 'no'.",
    "Send a compliment to the person above you in the turn order, in a poem.",
    "Post a screenshot of your last 3 Google Maps searches.",
    "Send the group a 'roast' of yourself, minimum 3 lines.",
    "Record a 10-second rap about this group and send it.",
    "Send a screenshot of your most embarrassing app usage stat this week.",
    "DM the group's most active member a compliment and screenshot their reaction.",
    "Send your current lock screen wallpaper.",
    "Type an entire message backwards and make the group guess it.",
    "Send a voice note in the most dramatic movie-trailer voice you can do.",
    "Post the oldest photo in your gallery, whatever it is.",
    "Send a screenshot of your last 5 messages sent (to anyone), unedited.",
    "Do an impression of a robot for your next 3 replies.",
    "Send a fake breaking-news headline about someone in this group.",
    "Record yourself explaining a random object near you like it's a TED Talk, 15 seconds.",
    "Change your bio/status to something the group decides for 1 hour.",
    "Send a screenshot of a chat where you were left on read.",
    "Text 'guess who' to a random contact and screenshot the confusion.",
    "Send a voice note doing your best celebrity impression.",
    "Post your screen time app breakdown for today.",
    "Send the group a fake motivational quote 'from yourself'.",
    "Reply to the next message with a rhyme, no matter how bad.",
    "Send a screenshot of the weather in your city right now with a dramatic caption.",
    "Record yourself saying a tongue twister 3 times fast.",
    "Send your most recent 'starred/saved' message from any chat.",
    "Post a one-star self-review like you're rating yourself on an app.",
    "Send the group a made-up conspiracy theory about this college.",
    "Type your next reply using only movie titles.",
    "Send a voice note pretending to interview yourself.",
    "Post a screenshot of your most-used emoji keyboard row.",
    "Send the group a 'breaking news' voice note about something trivial happening right now.",
    "DM someone outside this group 'you've won a prize' and screenshot their reply.",
    "Send your last voice message length (screenshot) and guess what it said from memory.",
    "Record a fake advertisement for this group, 15 seconds.",
    "Send the group a screenshot of your notification count right now.",
    "Reply using only questions for your next 3 messages.",
    "Send the most recent photo where you're not looking at the camera.",
    "Post a screenshot of your last 3 emoji reactions sent, and to what.",
    "Send a voice note singing 'Happy Birthday' to no one in particular.",
    "Text your sibling/roommate 'do you love me' and screenshot the reaction.",
    "Send the group your phone's storage breakdown screenshot.",
    "Record yourself doing the intro of a podcast about your day, 15 seconds.",
    "Send a fake 'apology statement' as if you did something scandalous.",
    "Post the first result when you search your own name online.",
    "Send a voice note narrating what you're doing right now like a nature documentary.",
    "Type your next message with zero vowels and let the group decode it.",
    "Send a screenshot of the last app you deleted and why (in caption).",
    "DM the group admin a formal 'complaint' about something silly.",
    "Send a voice note doing a dramatic reading of the group rules.",
    "Post your most recent 'liked' post from any social media.",
    "Send a screenshot of a random chat's last message (name blurred).",
    "Record yourself giving a fake weather forecast for your room.",
    "Send the group a 3-word review of your own life right now.",
    "Reply to the next message only using GIFs for a full minute.",
    "Send a voice note pretending you're a radio jockey introducing this group.",
    "Post a screenshot of your most recent alarm labels.",
    "Text 'we need to talk' to a random contact and screenshot the panic reply.",
    "Send the group a fake horoscope reading for someone else in the game.",
    "Record yourself trying to talk without moving your lips, 10 seconds.",
    "Send a screenshot of your last video call duration with anyone.",
    "Post the most-used word in your recent chats (check autocorrect suggestions).",
    "Send a voice note pitching this group chat as a Netflix show.",
    "DM a friend 'send help' with no context and screenshot their reply.",
    "Send the group your typing speed from an online typing test screenshot.",
    "Reply to the next 3 messages in third person only.",
    "Send a screenshot of the last thing you added to a cart but didn't buy.",
    "Record a 10-second fake commentary like it's a sports match, about anything nearby.",
    "Send the group a made-up 'fun fact' about yourself, convincingly.",
    "Post a screenshot showing how long you've had your current phone wallpaper (best guess).",
    "Send a voice note doing an over-the-top dramatic 'no' in different tones.",
    "Text someone 'check your email' when you haven't sent one, and screenshot their confusion.",
    "Send the group your last 3 autocorrect suggestions from your keyboard.",
    "Record yourself giving a 10-second 'acceptance speech' for winning this game.",
]
