# Would You Rather — question bank
#
# Each mode is just a list of (option_a, option_b) tuples.
# To add a new mode later: add a new list below, then register it
# in WYR_MODES inside wyr.py (one dict entry + one command).

NORMAL = [
    ("Have more time", "Have more money"),
    ("Always be 10 minutes late", "Always be 20 minutes early"),
    ("Read minds", "Be invisible"),
    ("Lose all your money", "Lose all your photos"),
    ("Have no internet for a month", "Have no AC/fan for a month"),
    ("Always have to whisper", "Always have to shout"),
    ("Never use social media again", "Never watch movies/shows again"),
    ("Fight one horse-sized duck", "Fight 100 duck-sized horses"),
    ("Know when you'll die", "Know how you'll die"),
    ("Have unlimited mess food but no AC in hostel", "Have AC but mess food is gone forever"),
    ("Retake every exam this semester", "Lose all your notes a day before exams"),
    ("Be famous but broke", "Be rich but unknown"),
    ("Have more time", "Have more money"),
    ("Always be 10 minutes late", "Always be 20 minutes early"),
    ("Read minds", "Be invisible"),
    ("Lose all your money", "Lose all your photos"),
    ("Have no internet for a month", "Have no AC/fan for a month"),
    ("Always have to whisper", "Always have to shout"),
    ("Never use social media again", "Never watch movies/shows again"),
    ("Fight one horse-sized duck", "Fight 100 duck-sized horses"),
    ("Know when you'll die", "Know how you'll die"),
    ("Have unlimited mess food but no AC in hostel", "Have AC but mess food is gone forever"),
    ("Retake every exam this semester", "Lose all your notes a day before exams"),
    ("Be famous but broke", "Be rich but unknown"),

    ("Always have to say everything on your mind", "Never speak again"),
    ("Be able to fly", "Be able to teleport"),
    ("Live without music", "Live without movies"),
    ("Have a rewind button for your life", "Have a pause button for your life"),
    ("Be the funniest person in the room", "Be the smartest person in the room"),
    ("Never feel cold again", "Never feel hot again"),
    ("Lose your sense of smell", "Lose your sense of taste"),
    ("Win a lottery but have to share it with everyone you know", "Win half as much but keep it all"),
    ("Have a photographic memory", "Have a 200 IQ"),
    ("Always know if someone is lying to you", "Always get away with lying"),
    ("Have free Wi-Fi everywhere forever", "Have free food everywhere forever"),
    ("Be stuck in a traffic jam for 3 hours", "Be stuck in a slow-moving queue for 3 hours"),
    ("Give up your phone for a week", "Give up your bed for a week"),
    ("Have to sing instead of talk for a day", "Have to dance everywhere you walk for a day"),
    ("Always have wet socks", "Always have a popcorn kernel stuck in your teeth"),
    ("Be able to talk to animals", "Be able to speak every human language"),
    ("Never have to sleep again", "Never have to eat again"),
    ("Have the power to undo one decision", "Have the power to see one decision's outcome before making it"),
    ("Live in a treehouse", "Live in a houseboat"),
    ("Have unlimited battery on your phone", "Have unlimited data on your phone"),
    ("Be really good at cooking", "Be really good at baking"),
    ("Have a personal chef", "Have a personal driver"),
    ("Wake up an hour early every day", "Stay up an hour later every night"),
    ("Be able to skip Mondays forever", "Get every Friday off forever"),
    ("Have your own private library", "Have your own private cinema"),
    ("Be able to control fire", "Be able to control water"),
    ("Never have a bad hair day", "Never have a pimple again"),
    ("Have to high-five everyone you meet", "Have to fist-bump everyone you meet"),
    ("Live without your phone", "Live without your laptop"),
    ("Always smell like fresh bread", "Always smell like coffee"),
    ("Have an extra hour every day", "Have an extra day every week"),
    ("Be a famous singer", "Be a famous actor"),
    ("Never get stuck in traffic again", "Never wait in line again"),
    ("Be able to time travel to the past", "Be able to time travel to the future"),
    ("Have the ability to pause time", "Have the ability to rewind time by 10 seconds"),
    ("Always win arguments but lose friends", "Always lose arguments but keep friends"),
    ("Have unlimited vacation days but average pay", "Have a huge salary but only 5 vacation days a year"),
    ("Be the best at one sport", "Be average at every sport"),
    ("Have a house with no kitchen", "Have a house with no bathroom"),
    ("Be allergic to chocolate", "Be allergic to cheese"),
    ("Always have to walk backwards in public", "Always have to skip instead of walk in public"),
    ("Lose your keys every week", "Lose your phone every week"),
    ("Have an unlimited supply of your favorite snack", "Have an unlimited supply of your favorite drink"),
    ("Live in a world with no rules", "Live in a world with too many rules"),
    ("Always have to tell the whole truth", "Always be allowed to tell white lies"),
    ("Be stuck with dial-up internet speed forever", "Be stuck with no GPS ever again"),
    ("Have a never-ending bowl of your favorite food", "Have a never-ending supply of money but only spendable on food"),
    ("Be able to talk your way out of any situation", "Be able to fight your way out of any situation"),
    ("Live next to a noisy airport", "Live next to a noisy railway station"),
    ("Have free movie tickets for life", "Have free concert tickets for life"),
    ("Never be able to use punctuation again", "Never be able to use capital letters again"),
    ("Have the power to make anyone laugh", "Have the power to make anyone agree with you"),
    ("Be the last person on Earth", "Be in a world with infinite copies of yourself"),
    ("Always have to take the stairs", "Always have to take the longest route"),
    ("Be famous on social media but hated", "Be unknown but loved by everyone who knows you"),
    ("Have to repeat your favorite year of life", "Skip straight to your 40s"),
    ("Have no taste buds", "Have no sense of touch"),
    ("Be able to breathe underwater", "Be able to survive without oxygen for 10 minutes"),
    ("Have your browser history made public", "Have your private messages made public"),
    ("Always lose your train of thought mid-sentence", "Always forget people's names right after meeting them"),
    ("Have an unlimited gym membership but no time", "Have plenty of time but no gym access"),
    ("Be stuck with the same playlist forever", "Never be able to listen to music with lyrics again"),
    ("Have a personal assistant", "Have a personal trainer"),
    ("Live in a tiny house with no debt", "Live in a huge house with a mortgage"),
    ("Have an eidetic memory but a weak immune system", "Have a normal memory but never get sick"),
    ("Always have a song stuck in your head", "Always have an itch you can't scratch"),
    ("Be able to instantly learn any skill", "Be able to instantly heal any injury"),
    ("Be the funniest person at a party", "Be the most interesting person at a party"),
    ("Travel the world but never settle down", "Settle down but never travel"),
    ("Have to wear the same outfit every day for a year", "Have to eat the same meal every day for a year"),
    ("Have an unbreakable phone screen", "Have an unbreakable laptop"),
    ("Be naturally talented but lazy", "Be average but extremely hardworking"),
    ("Live somewhere always sunny", "Live somewhere it always snows"),
    ("Have a job you hate but pays well", "Have a job you love but pays average"),
    ("Be able to skip small talk forever", "Be able to skip waiting rooms forever"),
    ("Always have perfect handwriting", "Always have perfect grammar"),
    ("Have a never-ending to-do list", "Have nothing to do at all"),
    ("Be able to fast-forward boring conversations", "Be able to rewind awkward conversations"),
    ("Have free public transport for life", "Have free parking for life"),
    ("Always know the weather a week in advance", "Always know your exam questions a week in advance"),
    ("Be the best dancer at every party", "Be the best singer at every karaoke night"),
    ("Have unlimited storage on your phone", "Have unlimited storage on cloud but with weak internet"),
    ("Live a life with no surprises", "Live a life full of surprises, good and bad"),
    ("Be able to talk to your past self", "Be able to talk to your future self"),
    ("Have a 4-day work week with longer hours", "Have a 5-day work week with shorter hours"),
    ("Be stuck on a deserted island alone", "Be stuck on a deserted island with someone annoying"),
    ("Have an extremely loud sneeze", "Have an extremely loud laugh"),
    ("Always wake up with messy hair", "Always wake up with dry lips"),
    ("Be able to instantly become fluent in any language", "Be able to instantly master any instrument"),
    ("Have a house that cleans itself", "Have a fridge that's always stocked"),
    ("Be famous for something embarrassing", "Be completely unknown forever"),
    ("Have to give a speech every day", "Have to take a test every day"),
    ("Have a private chef who only makes spicy food", "Have a private chef who only makes bland food"),
    ("Live without caffeine forever", "Live without sugar forever"),
    ("Have an unlimited book budget", "Have an unlimited travel budget"),
    ("Be able to remember every dream you have", "Never remember your dreams at all"),
    ("Have to use only voice notes to communicate", "Have to use only emojis to communicate"),
    ("Always be the designated driver", "Always be the one who plans the trip"),
    ("Have a 10-second delay on everything you say", "Have a 10-second delay on everything you hear"),
    ("Be the first to try new technology", "Be the last to try new technology"),
    ("Have unlimited likes on your posts but no comments", "Have unlimited comments on your posts but no likes"),
    ("Be able to talk to plants and have them respond", "Be able to talk to your pet and have it respond"),
    ("Have a really good memory for faces but not names", "Have a really good memory for names but not faces"),
    ("Have to redo your worst exam", "Have to redo your worst interview"),
    ("Be stuck in an elevator for 2 hours", "Be stuck in a waiting room for 5 hours"),
    ("Always have slow Wi-Fi at home", "Always have slow Wi-Fi at work"),
    ("Be known as the smart one in your friend group", "Be known as the funny one in your friend group"),
    ("Have a job with no boss but no security", "Have a job with a boss but full security"),
    ("Be able to control the weather", "Be able to control gravity"),
    ("Have a really long commute with no traffic", "Have a really short commute but always stuck in traffic"),
    ("Live with no mirrors anywhere", "Live with no clocks anywhere"),
    ("Have to always agree to plans last minute", "Have to always cancel plans last minute"),
    ("Be terrible at remembering jokes", "Be terrible at remembering directions"),
    ("Have an annoying ringtone you can't change", "Have an annoying notification sound you can't change"),
    ("Always overpack for trips", "Always underpack for trips"),
    ("Be able to instantly fix any broken relationship", "Be able to instantly know if a relationship will work out"),
    ("Have to redo your first year of college", "Have to redo your final year of college"),
    ("Have unlimited access to any one streaming platform", "Have limited access to all streaming platforms"),
    ("Be stuck doing group projects forever", "Be stuck doing everything solo forever"),
    ("Have a really strict morning routine", "Have a really chaotic morning routine"),
    ("Be the one who's always early to class", "Be the one who's always early to leave class"),
    ("Have to explain memes to people who don't get it", "Have to explain technology to people who don't get it"),
    ("Be able to skip the line at any store", "Be able to skip the line at any restaurant"),
    ("Have a really messy room but organized mind", "Have a really organized room but messy mind"),
    ("Live with unreliable electricity", "Live with unreliable water supply"),
    ("Always overthink small decisions", "Always underthink big decisions"),
    ("Be terrible with directions", "Be terrible with names"),
    ("Have to repeat the same conversation every day", "Have to meet a new stranger every day"),
    ("Be able to instantly know any answer on a test", "Be able to instantly finish any assignment"),
    ("Have an unlimited supply of stationery", "Have an unlimited supply of gadgets"),
    ("Be stuck with bad Wi-Fi during exams", "Be stuck with a noisy neighbor during exams"),
    ("Have a roommate who's always loud", "Have a roommate who's never around"),
    ("Be able to instantly clean your room", "Be able to instantly organize your files"),
    ("Have to attend every class on time but understand nothing", "Skip every class but ace every exam"),
    ("Be the one who always remembers birthdays", "Be the one who's always remembered on their birthday"),
    ("Have an annoying habit you can't break", "Have a friend with an annoying habit you can't change"),
    ("Live in a hostel with strict rules but cheap rent", "Live in a flat with no rules but expensive rent"),
    ("Be able to skip every Monday meeting", "Be able to skip every group assignment"),
    ("Have a really good sense of direction but bad memory", "Have a really good memory but bad sense of direction"),
    ("Always have to sit in the front row", "Always have to sit in the back row"),
    ("Be the one who plans every outing", "Be the one who never has to plan anything"),
    ("Have to always order the same dish at restaurants", "Have to always try something new and risk disliking it"),
    ("Be stuck with a strict alarm clock", "Be stuck with no alarm clock at all"),
    ("Have unlimited free coffee but no chai", "Have unlimited free chai but no coffee"),
    ("Be the friend who's always broke", "Be the friend who's always busy"),
    ("Have to walk everywhere", "Have to cycle everywhere"),
    ("Be able to skip airport security lines forever", "Be able to skip checkout lines forever"),
    ("Have a phone that never lags", "Have a laptop that never lags"),
    ("Always lose at board games", "Always lose at video games"),
    ("Be stuck with a slow charger forever", "Be stuck with a short charging cable forever"),
    ("Have to always take the longer but scenic route", "Have to always take the shorter but boring route"),
    ("Be known for your terrible jokes", "Be known for your terrible singing"),
    ("Have a job that's mentally exhausting but flexible hours", "Have a job that's physically exhausting but fixed hours"),
    ("Live with a strict curfew", "Live with no curfew but no privacy"),
    ("Be able to make perfect chai every time", "Be able to make perfect maggi every time"),
    ("Have to always carry an umbrella, rain or shine", "Have to always carry a water bottle everywhere"),
    ("Be stuck rewatching the same show forever", "Never be able to rewatch a show again"),
    ("Have unlimited access to one app", "Have limited access to every app"),
    ("Be the one who's always asked for notes", "Be the one who's always asking for notes"),
    ("Have a college with great food but boring classes", "Have a college with great classes but bad food"),
    ("Be able to nap anywhere instantly", "Be able to fall asleep instantly at night"),
    ("Have to always speak in rhymes", "Have to always speak in questions"),
    ("Be stuck with itchy clothing tags forever", "Be stuck with shoes that always feel a half-size off"),
    ("Have a really strong Wi-Fi signal but slow speed", "Have a weak Wi-Fi signal but fast speed"),
    ("Be the one who always finds the best deals", "Be the one who always finds the best shortcuts"),
    ("Have a pet that talks but only insults you", "Have a pet that talks but only compliments you"),
    ("Be able to instantly know if food is spicy before eating", "Be able to instantly know if food is too sweet before eating"),
    ("Live a life where everyone can hear your thoughts", "Live a life where you can hear everyone else's thoughts"),
    ("Be stuck with a permanently low phone battery icon", "Be stuck with a permanently spinning loading wheel"),
    ("Have a class that's always too hot", "Have a class that's always too cold"),
    ("Be the friend who gives the best advice", "Be the friend who gives the best gifts"),
    ("Have to redo your worst date", "Have to redo your worst job interview"),
    ("Be stuck with a printer that's always out of ink", "Be stuck with a Wi-Fi router that's always resetting"),
    ("Have a job where you work alone", "Have a job where you work in a big team"),
    ("Be able to eat anything without gaining weight", "Be able to sleep 4 hours and feel fully rested"),
    ("Always have to take the blame for group mistakes", "Never get credit for group successes"),
    ("Have a friend group that's always on time", "Have a friend group that's always running late"),
    ("Be stuck studying for finals during a heatwave", "Be stuck studying for finals during a power cut"),
    ("Have unlimited free auto-rickshaw rides", "Have unlimited free cab rides"),
    ("Be able to instantly mute any noisy classmate", "Be able to instantly mute any noisy neighbor"),
    ("Have a professor who's strict but fair", "Have a professor who's lenient but unpredictable"),
    ("Be stuck with a slow elevator every day", "Be stuck with no elevator at all"),
    ("Have to share your notes with everyone", "Never be allowed to borrow anyone's notes"),
    ("Be the one who always forgets their ID card", "Be the one who always forgets their charger"),
    ("Have an unlimited recharge plan but slow network", "Have a limited recharge plan but fast network"),
    ("Be stuck in a group chat that never stops buzzing", "Be left out of every group chat"),
    ("Have to eat hostel food forever", "Have to cook all your own meals forever"),
    ("Be the topic of campus gossip for a week", "Be completely forgotten by everyone for a week"),
    ("Date someone out of your league who's boring", "Date someone average who's hilarious"),
    ("Accidentally text your crush 'I love you'", "Accidentally like their 3-year-old photo"),
    ("Have your search history exposed to the group", "Have your DMs exposed to the group"),
    ("Get caught talking about your crush", "Get caught practicing a confession in the mirror"),
    ("Confess and get rejected", "Never confess and always wonder"),
    ("Have an awkward situationship for a year", "Be single forever in college"),
    ("Have more time", "Have more money"),
    ("Always be 10 minutes late", "Always be 20 minutes early"),
    ("Read minds", "Be invisible"),
    ("Lose all your money", "Lose all your photos"),
    ("Have no internet for a month", "Have no AC/fan for a month"),
    ("Always have to whisper", "Always have to shout"),
    ("Never use social media again", "Never watch movies/shows again"),
    ("Fight one horse-sized duck", "Fight 100 duck-sized horses"),
    ("Know when you'll die", "Know how you'll die"),
    ("Have unlimited mess food but no AC in hostel", "Have AC but mess food is gone forever"),
    ("Retake every exam this semester", "Lose all your notes a day before exams"),
    ("Be famous but broke", "Be rich but unknown"),
    ("Accidentally text your crush 'I love you'", "Accidentally like their 3-year-old photo"),
    ("Get caught talking about your crush", "Get caught practicing a confession in the mirror"),
    ("Confess and get rejected", "Never confess and always wonder"),
    ("Have your search history exposed to the group", "Have your browser history exposed to the group"),
    ("Your crush finds out you like them from someone else", "Your crush finds out you like them from a note"),
    ("Be caught crying over a breakup", "Be caught stalking an ex on Instagram"),
    ("Text the wrong person about your crush", "Send a voice note about your crush to the group chat"),
    ("Your parents walk in during a kiss", "Your parents walk in during a compromising moment"),
    ("Have an awkward situationship for a year", "Be single forever in college"),
    ("Date someone your best friend likes", "Date someone your parents hate"),
    ("Be cheated on", "Catch yourself about to cheat"),
    ("Have to explain why you ghosted someone", "Have to explain why you blocked someone"),
    ("Your ex shows up with your rival", "Your ex shows up with your best friend"),
    ("Get caught watching romantic movies alone", "Get caught reading romance novels in public"),
    ("Accidentally send a flirty message to a teacher/prof", "Accidentally send a flirty message to your parent's friend"),
    ("Have everyone know you're a virgin", "Have everyone know you're experienced"),
    ("Be friend-zoned by your crush", "Be crushed on by someone you're not interested in"),
    ("Propose and get rejected", "Reject someone's proposal in front of everyone"),
    ("See your crush kiss someone else", "See your crush fall in love with your rival"),
    ("Argue with your partner in public", "Cry with your partner in public"),
    ("Have your partner meet your friends and they hate them", "Have your friends try to convince you to break up"),
    ("Get caught taking screenshots of someone's story", "Get caught rewatching someone's Instagram posts"),
    ("Have to FaceTime your parents unexpectedly when with your partner", "Have your partner answer your phone when your parents call"),
    ("Be asked out by someone you have zero chemistry with", "Date someone amazing but have no attraction"),
    ("Your partner finds out you've been comparing them to an ex", "Your partner finds out you follow your ex on social media"),
    ("Have to admit you cried to a song", "Have to admit you watch reality TV obsessively"),
    ("Fall in love with someone completely wrong for you", "Have the perfect person be completely wrong for you"),
    ("Miss your chance to confess to your crush", "Confess and they do the same"),
    ("Be caught by your crush while gossiping about them", "Have your crush overhear you saying something bad"),
    ("Date someone who's your complete opposite", "Date someone exactly like you"),
    ("Have your crush be unattainable", "Have your crush like you back but the timing is wrong"),
    ("Get caught taking mirror selfies", "Get caught making TikTok videos"),
    ("Your crush says they like you but doesn't pursue it", "Your crush leads you on for months"),
    ("Have to introduce your partner to an ex", "Have to introduce your partner to your high school sweetheart"),
    ("Be ghosted by someone important", "Have to ghost someone important"),
    ("Get caught saving your crush's photos", "Get caught having a folder dedicated to your crush"),
    ("Accidentally like someone's embarrassing photo", "Accidentally comment on someone's private post"),
    ("Your partner forgets an important date", "Your partner plans a big surprise but you hate it"),
    ("Be the third wheel forever", "Always have people depend on you for dating advice"),
    ("Fall for someone already taken", "Have someone fall for you while you're taken"),
    ("Have your dirty secrets revealed in front of your crush", "Have your crush reveal secrets about you"),
    ("Be attracted to someone toxic", "Be rejected by someone you really want"),
    ("Get caught following your ex's new partner", "Get caught checking your ex's location"),
    ("Date someone your siblings disapprove of", "Date someone your friends don't trust"),
    ("Have permanent bad timing with someone you like", "Have someone perfect come at the worst time"),
    ("Get caught smelling someone's hoodie", "Get caught re-reading old messages"),
    ("Be obsessed with someone who's indifferent", "Have someone obsessed with you but you don't care"),
    ("Tell your crush how you feel and be rejected", "Never tell your crush and always wonder"),
    ("Date someone significantly older", "Date someone significantly younger"),
    ("Be with someone who loves you more", "Be with someone you love more"),
    ("Have your breakup be public knowledge", "Have your breakup be completely secret"),
    ("Fall in love during a short trip", "Miss your chance with someone you'll never see again"),
    ("Have a messy public breakup", "Have a silent mutual breakup"),
    ("Be the one who always texts first", "Be the one who always waits for texts"),
    ("Date someone who's still not over their ex", "Date someone who treats you like a rebound"),
    ("Get caught writing journal entries about your crush", "Get caught having a secret Pinterest board for your wedding"),
    ("Your crush date your enemy", "Your enemy date your best friend"),
    ("Have to pretend you're over your ex", "Have to watch your ex move on"),
    ("Be in love with someone who's emotionally unavailable", "Be with someone who's too emotionally dependent"),
    ("Have someone develop feelings for you overnight", "Develop feelings for someone who sees you as just a friend"),
    ("Get caught deleting texts after your crush reads them", "Get caught replying to texts while they're still typing"),
    ("Be asked to choose between two people you like", "Have the one you chose pick someone else"),
    ("Date someone who makes you insecure", "Date someone you're always reassuring"),
    ("Fall in love with a friend", "Have a friend fall in love with you"),
    ("Be in an on-and-off relationship", "Be in a stable but boring relationship"),
    ("Have your partner be overly protective", "Have your partner be too independent"),
    ("Date someone with completely different values", "Date someone with identical views but no spark"),
    ("Get caught liking all your crush's posts", "Get caught commenting flirty things on their posts"),
    ("Have to keep your relationship secret", "Have everyone know your business"),
    ("Date someone your family introduced you to", "Date someone your family explicitly told you not to"),
    ("Be the one always compromising", "Be with someone who never compromises"),
    ("Fall for someone you can't have", "Have access to someone but no feelings"),
    ("Accidentally call your partner by an ex's name", "Accidentally mention an ex during intimate time"),
    ("Have your partner be jealous of your friends", "Have your partner be distant from your family"),
    ("Date someone who's too clingy", "Date someone who's too distant"),
    ("Get caught stalking your crush's tagged photos", "Get caught checking your crush's activity status"),
    ("Have a one-sided attraction", "Have mutual attraction but terrible timing"),
    ("Be in love with someone who's moving away", "Be with someone who refuses to commit"),
    ("Date someone everyone warns you about", "Have everyone support a relationship that's toxic"),
    ("Have your private messages leaked", "Have your call history leaked"),
    ("Be caught using a face mask", "Be caught doing your hair"),
    ("Have your parents see your browsing history", "Have your friends see your search history"),
    ("Be caught posing for photos alone", "Be caught recording videos of yourself"),
    ("Your crush sees your drunk self", "Your crush sees you crying"),
    ("Accidentally send a typo-filled message to your crush", "Accidentally send a voice note instead of a text"),
    ("Have to explain your Spotify listening history", "Have to explain your YouTube watch history"),
    ("Be caught taking countless photos of your outfit", "Be caught checking your reflection everywhere"),
    ("Have your ex show up during your date", "Have your parents surprise visit during your date"),
    
    # New 100 unique (Set 2)
    ("Have all your passwords revealed", "Have all your DM conversations leaked"),
    ("Date someone who's overly religious", "Date someone who's aggressively atheist"),
    ("Be with someone who lies constantly", "Be with someone brutally honest about everything"),
    ("Have your crush date your sibling", "Have your sibling crush on your partner"),
    ("Get caught watching TikTok for 4 hours", "Get caught scrolling Instagram for an entire evening"),
    ("Be friend-zoned by someone you really loved", "Fall for someone who's completely out of your league"),
    ("Have to choose between your crush and best friend", "Have your crush and best friend date each other"),
    ("Be caught buying gifts for your crush", "Be caught stalking your crush's entire Instagram"),
    ("Your parents meet your crush and hate them", "Your crush meets your parents and they love them"),
    ("Date someone who only talks about themselves", "Date someone who never opens up emotionally"),
    ("Be cheated on during a trip", "Cheat and get caught immediately"),
    ("Have your partner choose their job over you", "Have your partner choose you over their dreams"),
    ("Get caught liking old photos of your crush", "Get caught un-liking your crush's photos"),
    ("Be in a relationship that's too perfect to be real", "Be in a relationship that feels completely fake"),
    ("Date someone your parents are obsessed with", "Date someone your parents despise"),
    ("Have your crush mention liking someone else", "Have your crush say you're perfect but not for them"),
    ("Be ghosted after a great date", "Have someone try really hard after a terrible date"),
    ("Date someone who's married to their job", "Date someone with no ambition whatsoever"),
    ("Be caught checking if your ex is online", "Be caught checking your ex's new partner's profile"),
    ("Have your crush see you at your absolute worst", "Have your crush think you're someone you're not"),
    ("Be with someone who's constantly comparing you to their ex", "Be with someone who never mentions their ex"),
    ("Date someone who's way too into their own looks", "Date someone who completely neglects their appearance"),
    ("Get caught writing fanfiction about your crush", "Get caught with a crush's fan account"),
    ("Have your partner spend more time with their phone than you", "Have your partner completely ignore technology"),
    ("Be in love with someone who views love as transactional", "Be with someone who's afraid of commitment"),
    ("Accidentally like your crush's private story", "Accidentally message your crush instead of friend"),
    ("Have your crush ask your friend out instead", "Have your friend ask your crush out"),
    ("Date someone who's obsessed with their ex", "Date someone who acts like their ex never existed"),
    ("Be the rebound", "Be the backup plan"),
    ("Have your partner's parents hate you", "Have your parents love someone you don't"),
    ("Get caught buying matching couple items", "Get caught planning your future alone"),
    ("Be with someone who's emotionally draining", "Be with someone completely emotionally unavailable"),
    ("Date someone with a worse financial situation", "Date someone obsessed with money"),
    ("Have your crush ask you out via text", "Have your crush never ask you out at all"),
    ("Be in a long-distance relationship that's unsustainable", "Be with someone unwilling to try long-distance"),
    ("Date someone your best friend is also interested in", "Have your best friend date someone you like"),
    ("Get caught deleting your search history after looking someone up", "Get caught having a detailed spreadsheet about your crush"),
    ("Be with someone who compares you to their best friend", "Be with someone who doesn't value your friendship"),
    ("Have a crush who only reaches out when they're drunk", "Have a crush who ghosts you when sober"),
    ("Date someone who brings up marriage on the first date", "Date someone who swears they'll never marry"),
    ("Be caught watching videos of your crush", "Be caught saving screenshots of your crush"),
    ("Have your partner prioritize their friend group over you", "Have your partner isolate you from your friends"),
    ("Be with someone who's still financially dependent on their parents", "Be with someone whose parents are overly involved"),
    ("Date someone who has completely different life goals", "Date someone with no goals at all"),
    ("Get caught posting cryptic tweets about your crush", "Get caught changing your status when they do"),
    ("Have your crush think you're weird", "Have your crush think you're boring"),
    ("Be in a relationship everyone gossips about", "Be in a relationship no one knows about"),
    ("Date someone who's constantly on dating apps", "Date someone who's never tried dating before"),
    ("Have your partner hide you from their social media", "Have your partner over-post about you"),
    ("Be with someone who says 'I love you' too early", "Be with someone who takes years to say it"),
    ("Date someone who's emotionally manipulative", "Date someone who's emotionally cold"),
    ("Get caught adding your crush to a private story", "Get caught mentioning your crush constantly"),
    ("Have your crush say you're like a brother/sister", "Have your crush only see you as a friend"),
    ("Be in love with someone who's in love with someone else", "Be with someone who's grateful but not in love"),
    ("Date someone who talks about their exes constantly", "Date someone who pretends exes don't exist"),
    ("Have your partner lie about little things", "Have your partner keep big secrets from you"),
    ("Be caught lurking in your crush's story viewers", "Be caught first to watch your crush's stories"),
    ("Have a crush who only looks at you when drunk", "Have a crush who avoids you completely sober"),
    ("Date someone with unresolved trauma", "Date someone who's too emotionally guarded"),
    ("Be with someone obsessed with labels", "Be with someone who refuses any commitment titles"),
    ("Have your crush ask 'What are we?' and you panic", "Have your crush act like you're nothing"),
    ("Get caught having your crush's location pinned", "Get caught checking when they're available"),
    ("Be with someone who's jealous of your opposite-gender friends", "Be with someone who has too many ex-lovers as friends"),
    ("Date someone whose family is chaotic", "Date someone whose family is too controlled"),
    ("Have your partner compare you during intimate moments", "Have your partner never compliment you"),
    ("Be in a relationship held together by guilt", "Be in a relationship held together by habit"),
    ("Date someone who's extremely pessimistic", "Date someone who's delusionally optimistic"),
    ("Have your crush say they need to 'focus on themselves'", "Have your crush suddenly move on completely"),
    ("Be caught having multiple tabs of your crush open", "Be caught checking your crush's location app"),
    ("Be caught rewatching your crush's stories", "Be caught taking screenshots of their stories"),
    ("Have a partner who's on their phone during sex", "Have a partner who's completely present"),
    ("Date someone who talks about their ex constantly", "Date someone who acts like they never existed"),
    ("Be with someone who's obsessed with social media", "Be with someone who avoids it completely"),
    ("Have your crush know all your secrets", "Have your crush know nothing about you"),
    ("Be in a relationship people actively root against", "Be in a relationship nobody knows about"),
    ("Date someone your horoscope warns you about", "Date someone your horoscope recommends"),
    ("Have a partner who cancels dates last minute", "Have a partner who's overly committed"),
    ("Be with someone who plays games", "Be with someone overly straightforward"),
    ("Get caught having your crush as your phone wallpaper", "Get caught having them as your lock screen"),
    ("Date someone who's still living with their ex", "Date someone who never mentions exes"),
    ("Have your crush friend-zone you gently", "Have your crush reject you harshly"),
    ("Be with someone who's chronically late", "Be with someone overly early"),
    ("Date someone who's never been in love", "Date someone who's been in love constantly"),
    ("Have a partner who loves PDA", "Have a partner who hates PDA"),
    ("Be with someone who's overly ambitious", "Be with someone with no goals"),
    ("Get caught watching couple TikToks alone", "Get caught saving couple posts"),
    ("Have your crush move on to someone hotter", "Have your crush move on to someone less attractive"),
    ("Be in love with someone emotionally stunted", "Be with someone too emotionally intelligent"),
    ("Date someone who ghosts you periodically", "Date someone who's too clingy"),
    ("Have a partner who's never alone", "Have a partner who's always alone"),
    ("Be with someone addicted to their ex", "Be with someone who never looks back"),
    ("Get caught checking your crush's location constantly", "Get caught checking their read receipts"),
    ("Have your crush say you're perfect but boring", "Have your crush say you're exciting but wrong"),
    ("Be in a situationship that lasts years", "Be in a committed relationship that lasts weeks"),
    ("Date someone who's too good on paper", "Date someone who's completely on paper wrong"),
    ("Have your partner betray your trust", "Have your partner question your loyalty"),
    ("Be with someone who checks their phone during dates", "Be with someone who leaves their phone off"),
    ("Get caught saving your crush's voice messages", "Get caught replaying their videos"),
    ("Have a partner who lies about their past", "Have a partner who overshares their past"),
    ("Be in a relationship destined to fail", "Be in a relationship that's too perfect"),
]

NSFW = [
    # Original 100
    ("Find out your partner slept with your parent in the past", "Find out your ex now sleeps with your parent"),
    ("Tease with hot wax", "Tease with ice cubes"),
    ("Feel no pleasure during sex", "Have everything you eat taste bad"),
    ("Give a lap dance", "Give a striptease"),
    ("Make love in the bathtub", "Make love under the shower"),
    ("Be with a partner you can't please sexually", "Be with a partner who can't please you sexually"),
    ("Have sex dressed as Santa", "Have sex dressed as a priest"),
    ("Send your nudes to a stranger", "Send your nudes to an ex"),
    ("Date someone out of your league who's boring", "Date someone average who's hilarious"),
    ("Have sex only in missionary position forever", "Have to try every position at least once"),
    ("Have a partner who's always in the mood", "Have a partner with a completely different libido"),
    ("Be watched by your partner", "Watch your partner with someone else"),
    ("Have sex with the lights on", "Have sex completely blindfolded"),
    ("Be handcuffed", "Be blindfolded"),
    ("Have a quickie in a risky place", "Have slow passionate sex at home"),
    ("Use toys in the bedroom", "Never use toys in the bedroom"),
    ("Have phone sex", "Have video sex"),
    ("Receive oral sex", "Give oral sex"),
    ("Have multiple orgasms easily", "Have difficulty reaching orgasm"),
    ("Be submissive", "Be dominant"),
    ("Have kinky sex", "Have vanilla sex forever"),
    ("Role play with your partner", "Never role play"),
    ("Have public sex", "Have sex in a semi-public place"),
    ("Share intimate photos with your partner", "Never share intimate photos"),
    ("Have sex on your first date", "Wait months before having sex"),
    ("Have spontaneous sex", "Plan every intimate encounter"),
    ("Be with someone who wants to film it", "Be with someone who forbids any recording"),
    ("Have morning sex", "Have late night sex"),
    ("Have tantric sex", "Have passionate wild sex"),
    ("Wear lingerie", "Wear nothing at all"),
    ("Use a sex dungeon", "Use a regular bedroom"),
    ("Have a one-night stand", "Have only committed relationships"),
    ("Be with someone very experienced", "Be with someone less experienced than you"),
    ("Have phone sex with a stranger", "Have video sex with someone you know"),
    ("Receive a massage with a happy ending", "Give a massage that leads somewhere"),
    ("Have your partner be jealous of your sexuality", "Have your partner encourage you to explore"),
    ("Abstain from sex for a year", "Have sex multiple times a day"),
    ("Use aphrodisiacs", "Use alcohol to set the mood"),
    ("Have sex during your period", "Avoid that time of the month"),
    ("Be with someone who talks a lot during sex", "Be with someone completely silent"),
    ("Have your partner be shy", "Have your partner be extremely confident"),
    ("Use whipped cream in the bedroom", "Use honey in the bedroom"),
    ("Have rough sex", "Have sensual, gentle sex"),
    ("Be tied up", "Tie your partner up"),
    ("Have a partner who's obsessed with foreplay", "Have a partner who wants to skip straight to it"),
    ("Have shower sex", "Have pool sex"),
    ("Be with someone who's very vocal", "Be with someone quiet"),
    ("Use a feather", "Use ice"),
    ("Have candlelit sex", "Have sex in complete darkness"),
    ("Wear a mask during sex", "Be completely exposed"),
    ("Have sex with music on", "Have sex in complete silence"),
    ("Use mirrors during sex", "Avoid seeing yourselves"),
    ("Have a partner who wants to watch porn together", "Have a partner who forbids porn"),
    ("Send a sexy selfie", "Receive one from your partner"),
    ("Have sex in a car", "Have sex on a boat"),
    ("Be completely shaved down there", "Have a full natural look"),
    ("Have sex against a wall", "Have sex on a desk"),
    ("Use chocolate during sex", "Use strawberries during sex"),
    ("Have your partner wear a costume", "Wear a costume yourself"),
    ("Have very long foreplay", "Get straight to the main event"),
    ("Have a partner who's very kinky", "Have a partner who prefers vanilla"),
    ("Be with someone who wants to experiment", "Be with someone set in their ways"),
    ("Have morning quickie sex", "Have slow, long evening sex"),
    ("Be with someone who's into roleplay", "Be with someone who finds it weird"),
    ("Use toys together", "Use toys separately"),
    ("Have sex in a sleeping bag", "Have sex in a hotel"),
    ("Wear sexy underwear", "Wear comfortable underwear"),
    ("Have a partner who wants to explore BDSM", "Have a partner who's strictly vanilla"),
    ("Use body oils during sex", "Use lotion during sex"),
    ("Have sex standing up", "Have sex lying down"),
    ("Be with someone who needs stimulation", "Be with someone who doesn't need much"),
    ("Have a partner with a foot fetish", "Have a partner with no specific fetish"),
    ("Use restraints", "Use nothing but hands"),
    ("Have sex in a tent", "Have sex in a mansion"),
    ("Be with someone who wants to be dominated", "Be with someone who wants to dominate"),
    ("Have a partner who wants constant variety", "Have a partner who likes routine"),
    ("Use edible underwear", "Use regular underwear"),
    ("Have sex with the TV on", "Have sex with no distractions"),
    ("Be with someone who wants to try everything", "Be with someone very specific in their desires"),
    ("Have a very high libido partner", "Have a partner with low libido"),
    ("Use massage oils", "Use lotion"),
    ("Have outdoor sex", "Have indoor sex only"),
    ("Be with someone who talks dirty", "Be with someone who prefers silence"),
    ("Use handcuffs", "Use ropes"),
    ("Have a partner who wants morning sex always", "Have a partner who only wants night sex"),
    ("Be with someone very flexible", "Be with someone not flexible at all"),
    ("Have sex in heels", "Have sex barefoot"),
    ("Use a vibrator", "Use other toys"),
    ("Have a partner obsessed with your body", "Have a partner who's emotionally connected"),
    ("Use lipstick during sex", "Avoid makeup"),
    ("Have a partner who's very giving", "Have a partner who's very selfish"),
    ("Use scented candles", "Use no scent at all"),
    ("Have passionate rough sex", "Have slow intimate sex"),
    ("Be with someone into roleplay scenarios", "Be with someone completely vanilla"),
    ("Use a bed", "Use furniture around the house"),
    ("Have sex in your parents' house", "Have sex in your partner's parents' house"),
    ("Be with someone who loves foreplay", "Be with someone who skips it entirely"),
    ("Have a partner who's very loud", "Have a partner who's completely quiet"),
    ("Use toys regularly", "Never use toys"),
    ("Have extremely short sessions", "Have extremely long sessions"),
    
    # New 100 unique (Set 2)
    ("Experiment with temperature play", "Experiment with sensation play"),
    ("Have sex in a friend's house", "Have sex in a public building"),
    ("Be completely silent during sex", "Be extremely vocal"),
    ("Have a partner who loves giving", "Have a partner who loves receiving"),
    ("Use food during intimacy", "Use ice during intimacy"),
    ("Be with someone who wants to incorporate others", "Be with someone who wants it to be private"),
    ("Have quickie sex only", "Have marathon sex sessions"),
    ("Use a swing during sex", "Use restraints during sex"),
    ("Have a partner who loves giving", "Have a partner who loves receiving"),
    ("Wear costumes frequently", "Never wear costumes"),
    ("Be with someone into feet", "Be with someone into other body parts"),
    ("Have very kinky preferences", "Have very vanilla preferences"),
    ("Use oils regularly", "Use other lubricants"),
    ("Have sex in different locations", "Have sex in the same place always"),
    ("Be completely hairless", "Have body hair everywhere"),
    ("Use a vibrator constantly", "Never use any toys"),
    ("Have a partner who wants to film", "Have a partner completely against filming"),
    ("Be dominant in the bedroom", "Be submissive in the bedroom"),
    ("Use dirty talk", "Prefer no talking"),
    ("Have sex after fights", "Avoid sex during conflicts"),
    ("Be with someone very endowed", "Be with someone average"),
    ("Have a partner who's into BDSM heavily", "Have a partner completely against BDSM"),
    ("Use whips or paddles", "Use soft restraints"),
    ("Have sex in a hot tub", "Have sex in a sauna"),
    ("Be watched during sex", "Watch your partner during sex"),
    ("Have a partner who wants voyeurism", "Have a partner completely private"),
    ("Use a dildo", "Use other toys"),
    ("Have sex with the door unlocked", "Have sex with maximum privacy"),
    ("Be with someone who wants multiple rounds", "Be with someone satisfied with one"),
    ("Have extremely frequent sex", "Have infrequent sex"),
    ("Use a vibrating toy", "Use a stationary toy"),
    ("Be with someone who wants anal play", "Be with someone strictly against it"),
    ("Have a partner who wants to try everything", "Have a partner with limited interests"),
    ("Use a blindfold constantly", "Never use a blindfold"),
    ("Be with someone who loves teasing", "Be with someone who wants immediate action"),
    ("Have sex standing up always", "Have sex lying down always"),
    ("Use multiple positions per session", "Stick to one position"),
    ("Be with someone who leaves marks", "Be with someone careful not to"),
    ("Have a partner who's very creative", "Have a partner who likes routine"),
    ("Use ice for teasing", "Use wax for teasing"),
    ("Have sex after drinking", "Have sex completely sober"),
    ("Be with someone who wants quickies", "Be with someone who wants marathon sessions"),
    ("Use a partner's body as the only toy", "Use multiple toys"),
    ("Have a partner obsessed with your pleasure", "Have a partner focused on their own"),
    ("Be with someone who watches porn", "Be with someone who doesn't"),
    ("Have very intense orgasms", "Have difficulty reaching orgasm"),
    ("Use a remote control toy", "Use toys you control"),
    ("Have a partner who's jealous of toys", "Have a partner encouraging of toys"),
    ("Be with someone who initiates sex", "Be the one who always initiates"),
    ("Have sex in dangerous places", "Have sex only in safe places"),
    ("Use roleplay often", "Never use roleplay"),
    ("Be with someone experimental", "Be with someone traditional"),
    ("Have a partner who loves your body", "Have a partner critical of your body"),
    ("Use multiple types of lube", "Use one specific lube"),
    ("Be with someone who wants to watch others", "Be with someone completely monogamous"),
    ("Have a partner who initiates everything", "Have a partner who never initiates"),
    ("Use a body-safe toy", "Use any toy"),
    ("Have a partner who's into tantric sex", "Have a partner who wants quickies"),
    ("Be with someone who wants to experiment weekly", "Be with someone satisfied with routine"),
    ("Use a couples' vibrator", "Use a solo vibrator"),
    ("Have extremely satisfying sex", "Have mediocre sex"),
    ("Be with someone who wants to try kink", "Be with someone completely vanilla"),
    ("Have a partner who's very communicative", "Have a partner who never talks"),
    ("Use a vibrator on your partner", "Have your partner use it on you"),
    ("Be with someone who wants constant novelty", "Be with someone who loves routine"),
    ("Have sex that lasts hours", "Have sex that lasts minutes"),
    ("Be with someone who wants maximum stimulation", "Be with someone who prefers gentle"),
    ("Use lubricant abundantly", "Use minimal or no lubricant"),
    ("Have a partner who's very experienced", "Have a partner who's inexperienced"),
    ("Be with someone kinky as hell", "Be with someone completely vanilla"),
    ("Have a partner obsessed with your reactions", "Have a partner who doesn't care"),
    ("Use toys you both picked out", "Use toys chosen by one partner"),
    ("Be with someone who wants to experiment constantly", "Be with someone set in their ways"),
    ("Have very passionate sex", "Have sex out of obligation"),
    ("Use roleplay with costumes", "Use roleplay without props"),
    ("Be with someone who gets you excited", "Be with someone you're not that into"),
    ("Have a partner who values your pleasure equally", "Have a partner focused on themselves"),
    ("Use bondage occasionally", "Never use bondage"),
    ("Be with someone who's into sensation play", "Be with someone into standard play"),
    ("Have sex multiple times daily", "Have sex once a week"),
    ("Use toys that vibrate intensely", "Use toys that vibrate gently"),
    ("Be with someone completely uninhibited", "Be with someone very reserved"),
    ("Have a partner who wants to involve friends", "Have a partner who only wants you"),
    ("Be with someone who's extremely flexible", "Be with someone with limited mobility"),
    ("Use toys from a store", "Use homemade toys"),
    ("Have a partner who wants to go raw", "Have a partner who insists on protection"),
    ("Be with someone who wants threesomes", "Be with someone strictly monogamous"),
    ("Use multiple lubes", "Use just one"),
    ("Have a partner who likes it rough", "Have a partner who likes it gentle"),
    ("Be with someone who wants swinging", "Be with someone against it completely"),
    ("Use bondage regularly", "Never use bondage"),
    ("Have a partner obsessed with positions", "Have a partner who's position agnostic"),
    ("Be with someone who orgasms easily", "Be with someone who struggles"),
    ("Use aphrodisiacs", "Use nothing but natural stimulation"),
    ("Have a partner who gets pleasure from giving", "Have a partner who needs to receive"),
    ("Be with someone very kinky", "Be with someone very vanilla"),
    ("Use a toy designed for couples", "Use solo toys"),
    ("Have a partner who's very experimental", "Have a partner who's traditional"),
    ("Be with someone who wants to record", "Be with someone completely against filming"),
    ("Have a partner who talks constantly", "Have a partner who's silent"),
]
