# Would You Rather — question bank
#
# Each mode is just a list of (option_a, option_b) tuples.
# To add a new mode later: add a new list below, then register it
# in WYR_MODES inside wyr.py (one dict entry + one command).

NORMAL = [
    ("Have more time", "Have more money"),
    ("Always be 10 minutes late", "Always be 20 minutes early"),
    ("Read minds", "Be invisible"),
    ("Lose all your money", "Lose all your photos"),
    ("Have no internet for a month", "Have no AC/fan for a month"),
    ("Always have to whisper", "Always have to shout"),
    ("Never use social media again", "Never watch movies/shows again"),
    ("Fight one horse-sized duck", "Fight 100 duck-sized horses"),
    ("Know when you'll die", "Know how you'll die"),
    ("Have unlimited mess food but no AC in hostel", "Have AC but mess food is gone forever"),
    ("Retake every exam this semester", "Lose all your notes a day before exams"),
    ("Be famous but broke", "Be rich but unknown"),
    ("Have more time", "Have more money"),
    ("Always be 10 minutes late", "Always be 20 minutes early"),
    ("Read minds", "Be invisible"),
    ("Lose all your money", "Lose all your photos"),
    ("Have no internet for a month", "Have no AC/fan for a month"),
    ("Always have to whisper", "Always have to shout"),
    ("Never use social media again", "Never watch movies/shows again"),
    ("Fight one horse-sized duck", "Fight 100 duck-sized horses"),
    ("Know when you'll die", "Know how you'll die"),
    ("Have unlimited mess food but no AC in hostel", "Have AC but mess food is gone forever"),
    ("Retake every exam this semester", "Lose all your notes a day before exams"),
    ("Be famous but broke", "Be rich but unknown"),

    ("Always have to say everything on your mind", "Never speak again"),
    ("Be able to fly", "Be able to teleport"),
    ("Live without music", "Live without movies"),
    ("Have a rewind button for your life", "Have a pause button for your life"),
    ("Be the funniest person in the room", "Be the smartest person in the room"),
    ("Never feel cold again", "Never feel hot again"),
    ("Lose your sense of smell", "Lose your sense of taste"),
    ("Win a lottery but have to share it with everyone you know", "Win half as much but keep it all"),
    ("Have a photographic memory", "Have a 200 IQ"),
    ("Always know if someone is lying to you", "Always get away with lying"),
    ("Have free Wi-Fi everywhere forever", "Have free food everywhere forever"),
    ("Be stuck in a traffic jam for 3 hours", "Be stuck in a slow-moving queue for 3 hours"),
    ("Give up your phone for a week", "Give up your bed for a week"),
    ("Have to sing instead of talk for a day", "Have to dance everywhere you walk for a day"),
    ("Always have wet socks", "Always have a popcorn kernel stuck in your teeth"),
    ("Be able to talk to animals", "Be able to speak every human language"),
    ("Never have to sleep again", "Never have to eat again"),
    ("Have the power to undo one decision", "Have the power to see one decision's outcome before making it"),
    ("Live in a treehouse", "Live in a houseboat"),
    ("Have unlimited battery on your phone", "Have unlimited data on your phone"),
    ("Be really good at cooking", "Be really good at baking"),
    ("Have a personal chef", "Have a personal driver"),
    ("Wake up an hour early every day", "Stay up an hour later every night"),
    ("Be able to skip Mondays forever", "Get every Friday off forever"),
    ("Have your own private library", "Have your own private cinema"),
    ("Be able to control fire", "Be able to control water"),
    ("Never have a bad hair day", "Never have a pimple again"),
    ("Have to high-five everyone you meet", "Have to fist-bump everyone you meet"),
    ("Live without your phone", "Live without your laptop"),
    ("Always smell like fresh bread", "Always smell like coffee"),
    ("Have an extra hour every day", "Have an extra day every week"),
    ("Be a famous singer", "Be a famous actor"),
    ("Never get stuck in traffic again", "Never wait in line again"),
    ("Be able to time travel to the past", "Be able to time travel to the future"),
    ("Have the ability to pause time", "Have the ability to rewind time by 10 seconds"),
    ("Always win arguments but lose friends", "Always lose arguments but keep friends"),
    ("Have unlimited vacation days but average pay", "Have a huge salary but only 5 vacation days a year"),
    ("Be the best at one sport", "Be average at every sport"),
    ("Have a house with no kitchen", "Have a house with no bathroom"),
    ("Be allergic to chocolate", "Be allergic to cheese"),
    ("Always have to walk backwards in public", "Always have to skip instead of walk in public"),
    ("Lose your keys every week", "Lose your phone every week"),
    ("Have an unlimited supply of your favorite snack", "Have an unlimited supply of your favorite drink"),
    ("Live in a world with no rules", "Live in a world with too many rules"),
    ("Always have to tell the whole truth", "Always be allowed to tell white lies"),
    ("Be stuck with dial-up internet speed forever", "Be stuck with no GPS ever again"),
    ("Have a never-ending bowl of your favorite food", "Have a never-ending supply of money but only spendable on food"),
    ("Be able to talk your way out of any situation", "Be able to fight your way out of any situation"),
    ("Live next to a noisy airport", "Live next to a noisy railway station"),
    ("Have free movie tickets for life", "Have free concert tickets for life"),
    ("Never be able to use punctuation again", "Never be able to use capital letters again"),
    ("Have the power to make anyone laugh", "Have the power to make anyone agree with you"),
    ("Be the last person on Earth", "Be in a world with infinite copies of yourself"),
    ("Always have to take the stairs", "Always have to take the longest route"),
    ("Be famous on social media but hated", "Be unknown but loved by everyone who knows you"),
    ("Have to repeat your favorite year of life", "Skip straight to your 40s"),
    ("Have no taste buds", "Have no sense of touch"),
    ("Be able to breathe underwater", "Be able to survive without oxygen for 10 minutes"),
    ("Have your browser history made public", "Have your private messages made public"),
    ("Always lose your train of thought mid-sentence", "Always forget people's names right after meeting them"),
    ("Have an unlimited gym membership but no time", "Have plenty of time but no gym access"),
    ("Be stuck with the same playlist forever", "Never be able to listen to music with lyrics again"),
    ("Have a personal assistant", "Have a personal trainer"),
    ("Live in a tiny house with no debt", "Live in a huge house with a mortgage"),
    ("Have an eidetic memory but a weak immune system", "Have a normal memory but never get sick"),
    ("Always have a song stuck in your head", "Always have an itch you can't scratch"),
    ("Be able to instantly learn any skill", "Be able to instantly heal any injury"),
    ("Be the funniest person at a party", "Be the most interesting person at a party"),
    ("Travel the world but never settle down", "Settle down but never travel"),
    ("Have to wear the same outfit every day for a year", "Have to eat the same meal every day for a year"),
    ("Have an unbreakable phone screen", "Have an unbreakable laptop"),
    ("Be naturally talented but lazy", "Be average but extremely hardworking"),
    ("Live somewhere always sunny", "Live somewhere it always snows"),
    ("Have a job you hate but pays well", "Have a job you love but pays average"),
    ("Be able to skip small talk forever", "Be able to skip waiting rooms forever"),
    ("Always have perfect handwriting", "Always have perfect grammar"),
    ("Have a never-ending to-do list", "Have nothing to do at all"),
    ("Be able to fast-forward boring conversations", "Be able to rewind awkward conversations"),
    ("Have free public transport for life", "Have free parking for life"),
    ("Always know the weather a week in advance", "Always know your exam questions a week in advance"),
    ("Be the best dancer at every party", "Be the best singer at every karaoke night"),
    ("Have unlimited storage on your phone", "Have unlimited storage on cloud but with weak internet"),
    ("Live a life with no surprises", "Live a life full of surprises, good and bad"),
    ("Be able to talk to your past self", "Be able to talk to your future self"),
    ("Have a 4-day work week with longer hours", "Have a 5-day work week with shorter hours"),
    ("Be stuck on a deserted island alone", "Be stuck on a deserted island with someone annoying"),
    ("Have an extremely loud sneeze", "Have an extremely loud laugh"),
    ("Always wake up with messy hair", "Always wake up with dry lips"),
    ("Be able to instantly become fluent in any language", "Be able to instantly master any instrument"),
    ("Have a house that cleans itself", "Have a fridge that's always stocked"),
    ("Be famous for something embarrassing", "Be completely unknown forever"),
    ("Have to give a speech every day", "Have to take a test every day"),
    ("Have a private chef who only makes spicy food", "Have a private chef who only makes bland food"),
    ("Live without caffeine forever", "Live without sugar forever"),
    ("Have an unlimited book budget", "Have an unlimited travel budget"),
    ("Be able to remember every dream you have", "Never remember your dreams at all"),
    ("Have to use only voice notes to communicate", "Have to use only emojis to communicate"),
    ("Always be the designated driver", "Always be the one who plans the trip"),
    ("Have a 10-second delay on everything you say", "Have a 10-second delay on everything you hear"),
    ("Be the first to try new technology", "Be the last to try new technology"),
    ("Have unlimited likes on your posts but no comments", "Have unlimited comments on your posts but no likes"),
    ("Be able to talk to plants and have them respond", "Be able to talk to your pet and have it respond"),
    ("Have a really good memory for faces but not names", "Have a really good memory for names but not faces"),
    ("Have to redo your worst exam", "Have to redo your worst interview"),
    ("Be stuck in an elevator for 2 hours", "Be stuck in a waiting room for 5 hours"),
    ("Always have slow Wi-Fi at home", "Always have slow Wi-Fi at work"),
    ("Be known as the smart one in your friend group", "Be known as the funny one in your friend group"),
    ("Have a job with no boss but no security", "Have a job with a boss but full security"),
    ("Be able to control the weather", "Be able to control gravity"),
    ("Have a really long commute with no traffic", "Have a really short commute but always stuck in traffic"),
    ("Live with no mirrors anywhere", "Live with no clocks anywhere"),
    ("Have to always agree to plans last minute", "Have to always cancel plans last minute"),
    ("Be terrible at remembering jokes", "Be terrible at remembering directions"),
    ("Have an annoying ringtone you can't change", "Have an annoying notification sound you can't change"),
    ("Always overpack for trips", "Always underpack for trips"),
    ("Be able to instantly fix any broken relationship", "Be able to instantly know if a relationship will work out"),
    ("Have to redo your first year of college", "Have to redo your final year of college"),
    ("Have unlimited access to any one streaming platform", "Have limited access to all streaming platforms"),
    ("Be stuck doing group projects forever", "Be stuck doing everything solo forever"),
    ("Have a really strict morning routine", "Have a really chaotic morning routine"),
    ("Be the one who's always early to class", "Be the one who's always early to leave class"),
    ("Have to explain memes to people who don't get it", "Have to explain technology to people who don't get it"),
    ("Be able to skip the line at any store", "Be able to skip the line at any restaurant"),
    ("Have a really messy room but organized mind", "Have a really organized room but messy mind"),
    ("Live with unreliable electricity", "Live with unreliable water supply"),
    ("Always overthink small decisions", "Always underthink big decisions"),
    ("Be terrible with directions", "Be terrible with names"),
    ("Have to repeat the same conversation every day", "Have to meet a new stranger every day"),
    ("Be able to instantly know any answer on a test", "Be able to instantly finish any assignment"),
    ("Have an unlimited supply of stationery", "Have an unlimited supply of gadgets"),
    ("Be stuck with bad Wi-Fi during exams", "Be stuck with a noisy neighbor during exams"),
    ("Have a roommate who's always loud", "Have a roommate who's never around"),
    ("Be able to instantly clean your room", "Be able to instantly organize your files"),
    ("Have to attend every class on time but understand nothing", "Skip every class but ace every exam"),
    ("Be the one who always remembers birthdays", "Be the one who's always remembered on their birthday"),
    ("Have an annoying habit you can't break", "Have a friend with an annoying habit you can't change"),
    ("Live in a hostel with strict rules but cheap rent", "Live in a flat with no rules but expensive rent"),
    ("Be able to skip every Monday meeting", "Be able to skip every group assignment"),
    ("Have a really good sense of direction but bad memory", "Have a really good memory but bad sense of direction"),
    ("Always have to sit in the front row", "Always have to sit in the back row"),
    ("Be the one who plans every outing", "Be the one who never has to plan anything"),
    ("Have to always order the same dish at restaurants", "Have to always try something new and risk disliking it"),
    ("Be stuck with a strict alarm clock", "Be stuck with no alarm clock at all"),
    ("Have unlimited free coffee but no chai", "Have unlimited free chai but no coffee"),
    ("Be the friend who's always broke", "Be the friend who's always busy"),
    ("Have to walk everywhere", "Have to cycle everywhere"),
    ("Be able to skip airport security lines forever", "Be able to skip checkout lines forever"),
    ("Have a phone that never lags", "Have a laptop that never lags"),
    ("Always lose at board games", "Always lose at video games"),
    ("Be stuck with a slow charger forever", "Be stuck with a short charging cable forever"),
    ("Have to always take the longer but scenic route", "Have to always take the shorter but boring route"),
    ("Be known for your terrible jokes", "Be known for your terrible singing"),
    ("Have a job that's mentally exhausting but flexible hours", "Have a job that's physically exhausting but fixed hours"),
    ("Live with a strict curfew", "Live with no curfew but no privacy"),
    ("Be able to make perfect chai every time", "Be able to make perfect maggi every time"),
    ("Have to always carry an umbrella, rain or shine", "Have to always carry a water bottle everywhere"),
    ("Be stuck rewatching the same show forever", "Never be able to rewatch a show again"),
    ("Have unlimited access to one app", "Have limited access to every app"),
    ("Be the one who's always asked for notes", "Be the one who's always asking for notes"),
    ("Have a college with great food but boring classes", "Have a college with great classes but bad food"),
    ("Be able to nap anywhere instantly", "Be able to fall asleep instantly at night"),
    ("Have to always speak in rhymes", "Have to always speak in questions"),
    ("Be stuck with itchy clothing tags forever", "Be stuck with shoes that always feel a half-size off"),
    ("Have a really strong Wi-Fi signal but slow speed", "Have a weak Wi-Fi signal but fast speed"),
    ("Be the one who always finds the best deals", "Be the one who always finds the best shortcuts"),
    ("Have a pet that talks but only insults you", "Have a pet that talks but only compliments you"),
    ("Be able to instantly know if food is spicy before eating", "Be able to instantly know if food is too sweet before eating"),
    ("Live a life where everyone can hear your thoughts", "Live a life where you can hear everyone else's thoughts"),
    ("Be stuck with a permanently low phone battery icon", "Be stuck with a permanently spinning loading wheel"),
    ("Have a class that's always too hot", "Have a class that's always too cold"),
    ("Be the friend who gives the best advice", "Be the friend who gives the best gifts"),
    ("Have to redo your worst date", "Have to redo your worst job interview"),
    ("Be stuck with a printer that's always out of ink", "Be stuck with a Wi-Fi router that's always resetting"),
    ("Have a job where you work alone", "Have a job where you work in a big team"),
    ("Be able to eat anything without gaining weight", "Be able to sleep 4 hours and feel fully rested"),
    ("Always have to take the blame for group mistakes", "Never get credit for group successes"),
    ("Have a friend group that's always on time", "Have a friend group that's always running late"),
    ("Be stuck studying for finals during a heatwave", "Be stuck studying for finals during a power cut"),
    ("Have unlimited free auto-rickshaw rides", "Have unlimited free cab rides"),
    ("Be able to instantly mute any noisy classmate", "Be able to instantly mute any noisy neighbor"),
    ("Have a professor who's strict but fair", "Have a professor who's lenient but unpredictable"),
    ("Be stuck with a slow elevator every day", "Be stuck with no elevator at all"),
    ("Have to share your notes with everyone", "Never be allowed to borrow anyone's notes"),
    ("Be the one who always forgets their ID card", "Be the one who always forgets their charger"),
    ("Have an unlimited recharge plan but slow network", "Have a limited recharge plan but fast network"),
    ("Be stuck in a group chat that never stops buzzing", "Be left out of every group chat"),
    ("Have to eat hostel food forever", "Have to cook all your own meals forever"),
    ("Be the topic of campus gossip for a week", "Be completely forgotten by everyone for a week"),
]

NSFW = [
    ("Date someone out of your league who's boring", "Date someone average who's hilarious"),
    ("Accidentally text your crush 'I love you'", "Accidentally like their 3-year-old photo"),
    ("Have your search history exposed to the group", "Have your DMs exposed to the group"),
    ("Get caught talking about your crush", "Get caught practicing a confession in the mirror"),
    ("Confess and get rejected", "Never confess and always wonder"),
    ("Have an awkward situationship for a year", "Be single forever in college"),
]
